### ISSUE TITLE
Site keep bouncing between url with/without trailing slash

### ISSUE THREAD

**Issue by darrenchiu** [nuxt-modules/i18n#1323]
### Version
@nuxtjs/i18n: 7.0.3
nuxt: 2.15.7

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

### Reproduction Link
Can try out at https://feature-test-old-version.dtfly0xvnnjyx.amplifyapp.com/courses/
You will see that the page keep refreshing and the url keep bouncing between the 2 urls.

### Steps to reproduce
When deployed to AWS Amplify, it works fine if you are entering the site from home page. But if you are trying to refresh a page or enter the site from a non-homepage, then it would keep redirecting between url with slash and url without slash (e.g. between `/courses` and `/courses/`)

However, it works perfectly on local environment

### What is Expected?
If you enter a page directly, it should not bounce between the slash and no-slash version repeatedly.

### What is actually happening?
if you are trying to refresh a page or enter the site from a non-homepage, then it would keep redirecting between url with slash and url without slash (e.g. between `/courses` and `/courses/`)

**Comment by rchl** [comment]
Looks like #1292.

Different servers have different behaviors regarding trailing slashes. Some redirect automatically, some don't.

When deciding whether I should redirect I could possibly ignore the differences in trailing slash but it could lead to other issues.

Having an example repo would help in getting to it quicker.

**Comment by darrenchiu** [comment]
Hi @rchl , I have built a minimum working repo to demonstrate this. This only happens when I deploy it to static hosting (i am using AWS amplify)

Repo: https://github.com/darrenchiu/i18n-bug-study
Path to replicate the issue: https://master.d1bhwix5uje0du.amplifyapp.com/inspire/

Would appreciate if you can take a look in this. If you can guide me a bit, I am also happy to contribute to create a fix and PR.

**Comment by darrenchiu** [comment]
AWS Amplify Build Script FYI:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run generate
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```
